## Implementations of two functions that cache the inverse of a matrix 

## Generates a custom matrix that can cache the inverse of itself
makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
        get <- function() {
                x
        }
        set_inverse <- function(inverse) {
                inv <<- inverse
        }
        get_inverse <- function() {
                inv
        }
        list(
                set = set,
                get = get,
                set_inverse = set_inverse,
                get_inverse = get_inverse
        )
}


## Computes the inverse of the the custom matrix generated by the function 
## 'makeCacheMatrix'.
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$get_inverse()
        if (!is.null(inv)) {
                message("Retrieving cached inverse...")
                return(inv)
        }
        mat <- x$get()
        inv <- solve(mat, ...)
        x$set_inverse(inv)
        inv
}
